import Head from 'next/head'
import styles from '../styles/home.module.scss'


export default function App({ Component, pageProps }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;700&display=swap" rel="stylesheet"></link> */}
      </Head>
      
      <Component {...pageProps} />
    </div>
  )
}
